### ISSUE TITLE
Editace nefunguje v IE7(?)

### ISSUE THREAD

**Issue by zbycz** [zbycz/casopisy#13]
![image](https://f.cloud.github.com/assets/385047/1691753/e223c79a-5e68-11e3-8ef5-ad52ca2e066e.png)

**Comment by MilanLochovsky** [comment]
Jen kdyby to někdo chtěl debugovat, tak protože asi nikdo nemá IE7 doma, tak stačí novější (třeba u mě IE11) a tam si zapnout vývojářskou konzoli (F12) a přepnout se v záložce Emulace na IE7. Dělá to tedy to samé.

**Comment by zbycz** [comment]
No vida, to jsem neznal. Každpoádně IE7 už ja pasé. V novém to funguje. Zavírám.

**Comment by MilanLochovsky** [comment]
Souhlasím. Já jsem na to jen koukal. Ale také jsem neměl chuť to nějak řešit, byť by to bylo vyřešitelné.
