### ISSUE TITLE
Neplatný certifikát pro casopisy.skauting.cz

### ISSUE THREAD

**Issue by fmasa** [zbycz/casopisy#21]
Koukal jsem, že kromě casopisy.skaut.cz existuje ještě doména casopisy.skauting.cz (na kterou se i v některých článcích na Křižovatce odkazuje). Vzhledem k tomu, že se teď web přesměrovává na https verzi, tak to umře na neplatným certifikátu (je tam LE certifikát jen pro casopisy.skaut.cz)

Viz https://www.sslshopper.com/ssl-checker.html#hostname=https://casopisy.skauting.cz/

**Comment by sinacek** [comment]
Certifikát už jsme dogenerovali. @zbycz mohl bys udělat přesměrování jen na tu adresu skaut.cz?

**Comment by zbycz** [comment]
Dík! Přesměrování jsem nastavil: https://github.com/zbycz/casopisy/commit/881445200943dbc566a004a4a441be89624b9b85
