### ISSUE TITLE
Načítání seznamu posledních čísel

### ISSUE THREAD

**Issue by kalich5** [zbycz/casopisy#22]
Měl bych dotaz, dá se nějak načítat seznam posledních čísel? Jak podle typu časopisu, tak i třeba když bych chtěl někde na webu zobrazit třeba "poslední 3 čísla nějakého časopisu"

Jde to nějak?

**Comment by zbycz** [comment]
Apičko umí jen "aktuální čísla" a "hledání".
Ale asi by neměl být problém to dopsat - viz [ApiPresenter.php](https://github.com/zbycz/casopisy/blob/master/app/FrontModule/presenters/ApiPresenter.php)

Jak by sis to představoval?
Něco jako https://casopisy.skaut.cz/api/posledni-cisla?casopis=skaut ?

**Comment by kalich5** [comment]
Uvažoval jsem o možnosti zobrazit poslední čísla časopisů na střediskovém (obvodním, oddílovém) webu. Mělo by to být jako jednoduchý plugin pro WordPress, možnost zobrazit ty poslední čísla (všechny, nebo jen vybraného druhu časopisu) na webu. A to buď přes widget někde napevno, nebo přes shordcode někde na stránce kam by se to hodilo.

**Comment by zbycz** [comment]
Ok, hotovo. Viz
URL: https://casopisy.skaut.cz/api/posledni-cisla?casopis=skaut
URL: https://casopisy.skaut.cz/api/posledni-cisla?casopis=svetylko&pocet=1
