### ISSUE TITLE
Nefunkční přihlašování přes skautIS

### ISSUE THREAD

**Issue by jan-stanek** [zbycz/casopisy#23]
![screenshot-2018-5-10 skautske casopisy on-line](https://user-images.githubusercontent.com/11959693/39890410-fa58dbde-549a-11e8-979c-8bd83a27610d.png)

**Comment by zbycz** [comment]
Dík vypadá to na externí chybu, řeším s dotyčnými.

**Comment by jan-stanek** [comment]
Jen doplním, že by to nemělo souviset s tou chybou, proč nefunguje Křižovatka. V té době ještě fungovala.

**Comment by jan-stanek** [comment]
Už funguje

**Comment by zbycz** [comment]
Dík, na ústředí nic nevěděli, každopádáně je fajn, že se to samo vyřešilo :)
