### ISSUE TITLE
Hezké adresy pro konkrétní číslo: casopisy.skaut.cz/svetylko2013-01

### ISSUE THREAD

**Issue by zbycz** [zbycz/casopisy#8]
formát rok-měsíc

**Comment by MilanLochovsky** [comment]
Tak nejrychleji by to šlo vyřešit přesměrováním 301. :) Ale to asi není to co se chce...

**Comment by zbycz** [comment]
No vlastně bych řekl, že už to není tak aktuální. V tištěných časopisech i všude jinde jsou normálně odkazy typu casopisy.skaut.cz/svetylko/245 a nezdá se že by to vadilo. Zavírám.

**Comment by MilanLochovsky** [comment]
ale kdyby se udělal aspoň fomrát casopis/rocnik/cislo, tak by to bylo pěkné a přehledné. ;) Ale jako na funkci to nemá vliv (https://www.youtube.com/watch?v=aW5gpYsmvFI).

**Comment by zbycz** [comment]
:-)

Ono by to nebylo tak snadné - číslo vydaní nemusí být unikátní, občas je časopis pojmenovaný "speciál" + jiné pravidla pro knihovnu. No, moc práce, málo užitku.

**Comment by MilanLochovsky** [comment]
To pak jo...
